### ISSUE TITLE
windows support?

### ISSUE THREAD

**Issue by psteinb** [spomjaksilp/pyMeCom#1]
Hi, 
We are trying to compile the demo code for MeCOMAPI 0.42 under Windows7 and MS visual studio 2017 and don't get anywhere (numerous errors break the build). The prebuilt example binary works though.

We wanted to give this python interface a shot. Was it ever tested under windows? If so, with what level of success?
Best,
P

**Comment by timhellwig** [comment]
Hi,
I just successfully made a basic test of the interface in Windows. Connecting and getting of parameters worked out of the box.
Best regards,
Tim

**Comment by psteinb** [comment]
Ok, that sounds promising. We will give it a shot. Can you give more details about the environment you performed that test in? Windows version, MSVC version, Python Version, ...

**Comment by ttuibk** [comment]
I also just got the example code at the end of mecom.py to work.

Anaconda 64 bit.  Win 10.  Python 3.6.5.  TEC-1091.  FTDI USB-RS485 cable.  I just changed the port from "/dev/ttyUSB0" to "COM4" (the port that showed up for the FTDI device in the device manager).

**Comment by psteinb** [comment]
@ttuibk so you are using the windows subsystem on Win10?

**Comment by spomjaksilp** [comment]
@ttuibk I really cannot speak for windows here since I have never tested it. The package in question is the following https://github.com/pyserial/pyserial or https://anaconda.org/anaconda/pyserial in conda.

**Comment by spomjaksilp** [comment]
I will close this now. If anyone wants to try this on Windows, feel free and submit a PR.
