### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by mkardan** [spomjaksilp/pyMeCom#10]
Hello again, 

Thank you for your great code, just managed to talk to My TEC-1090-HV. Can I ask a quick question hopefully; are you able to advise how can I reset the device through the Python script please? I couldn't find the reset register id in TEC Controller Communication Protocol, I could only find this in MeCom Spec:
![image](https://user-images.githubusercontent.com/54703028/83451615-2ea29500-a44f-11ea-82ca-56bb9fa1a2c7.png)

Many thanks,
MKardan

**Comment by timhellwig** [comment]
Hello again,

the current library does not support RS. There are two PR open that implement that. You could checkout my branch for example https://github.com/timhellwig/pyMeCom
that implements RS commands as well as support for laser diode drivers from Meerstetter

**Comment by mkardan** [comment]
Many thanks for your great help. Will try it tomorrow.

**Comment by spomjaksilp** [comment]
@mkardan I guess we an close this now since I merged @timhellwig PR including these changes
