### ISSUE TITLE
Sequence counter overflows

### ISSUE THREAD

**Issue by raffaelesury** [spomjaksilp/pyMeCom#11]
The sequence counter in the frame is an UINT16 and overflows at 0xFFFF, but the SEQUENCE_COUNTER variable is a Python "int" and just keeps being incremented. 
This gives a sequence number error. 

This can be fixed by modifying the _inc function in mecom.py so that it catches the value crossing the limit and resets it.

**Comment by timhellwig** [comment]
Hi Raffael,

i am not sure how active the author is still on this project. I fixed it in my fork (https://github.com/timhellwig/pyMeCom) mocking an overflow using modulo 2**16.

You can refer your customers to it if it helps. I am currently not implementing new features after the LDD implementation but I can probably continue to fix these kind of little bugfixes.

All the best, 
Tim

**Comment by raffaelesury** [comment]
I think your edits have been pulled, so this is solved.
