### ISSUE TITLE
Question: Channel Selection , how?

### ISSUE THREAD

**Issue by gittyhub2018** [spomjaksilp/pyMeCom#19]
Hello,

I have a little question to your pyMeCom Library: How can I select the Channel to set the parameter's?
I want to use the channels independently and at the moment I do not know where I can tell the TEC which channel I want to configure. I use a TEC-1123 with two Channels.

Thank you for your help.

Sincerely yours,

gittyhub2018

**Comment by gittyhub2018** [comment]
Problem is solved.

**Comment by timhellwig** [comment]
Hi @gittyhub2018 would you mind share your solution if somebody else runs into this problem?
