### ISSUE TITLE
floating point parameters error

### ISSUE THREAD

**Issue by ttuibk** [spomjaksilp/pyMeCom#3]
For the control parameters which take a FLOAT32 input, set_parameter returns FALSE if the part to the right of the decimal point is not a rational binary fraction.  Some kind of floating point precision issue?

examples where set_parameter returns TRUE:  1.0, 1.25, 1.375

examples where set_parameter returns FALSE:  0.3, 1.1, 1.4

I "fixed" it by changing the set_parameter method:

was        return value == value_set

now       return value == round(value_set,6)

**Comment by marc-haberstroh** [comment]
This issue has been fixed with the commit on August 30, 2018.
https://github.com/spomjaksilp/pyMeCom/commit/22ce55d7a2d5b5c8fae7146c9ce188f804512732#diff-2ab1910e9f7734d75b6409f71e7fbc0746d039d1a4ae22d966ccbb63cbe052c9
