### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by Jerome-Neanne** [spomjaksilp/pyMeCom#4]
Hi,

I used your code for my project (I initially thought this was official Meerstetter lib as it is referenced on their Web Site).
I plan to redistribute your code in that context.
More detail about the project can be found here: https://baylibre.com/tpmp-power-measurement-platform/

I'm in trouble on legal aspects because your code does not include any license file...
I plan to provide my project under BSD-3 license as it will be released open-source.

I can provide an example of license file and submit a pull request if you're OK with this.

Anyway, any license is OK for me as soon as it's clarified.

Please let me know your position.

**Comment by spomjaksilp** [comment]
Hi,
well sry answering that late. My PhD got me hooked quite a bit. I'll look into that.

**Comment by spomjaksilp** [comment]
@Jerome-Neanne Do I am heavily thinking about using the MIT license. IMHO that should work in your case, please share your thoughts.

**Comment by tt-aqt** [comment]
Having the same problem here.  MIT is fine.
